### ISSUE TITLE
Required library was not found

### ISSUE THREAD

**Issue by JustAPieOP** [natanbc/lavadsp#76]
Hello, i have trouble while using lavadsp, i can't use lavadsp because the required library wasn't found. Are there any additional setups that i skipped?

**Comment by natanbc** [comment]
Where did you get the library? The jar on jcenter has the natives.

**Comment by JustAPieOP** [comment]
i got it on jcenter, nowhere else

**Comment by JustAPieOP** [comment]
after adding the dependencies to my project, do i need to do additional setup?

**Comment by JustAPieOP** [comment]
This is my stacktrace btw
```
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre NativeLibraryLoader  INFO   Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$290/0x0000000000000000@7052ea69
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre NativeLibraryLoader  INFO   Native library libmpg123-0: successfully loaded.
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre NativeLibraryLoader  INFO   Native library connector: loading with filter null
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre NativeLibraryLoader  INFO   Native library connector: successfully loaded.
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre NativeLibLoader      INFO   Native library timescale: loading with parts [Part{feature=X86.avx2, part=avx2}]
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre NativeLibLoader      INFO   Native library detector: loading with parts []
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre NativeLibLoader      ERROR  Native library detector: loading failed.
java.lang.UnsatisfiedLinkError: Required library was not found
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:161)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.nativeloader.DetectorLoader.load0(DetectorLoader.java:17)
	at com.github.natanbc.nativeloader.DetectorLoader.loadDetector(DetectorLoader.java:11)
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:150)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.lavadsp.natives.TimescaleNativeLibLoader.loadTimescaleLibrary(TimescaleNativeLibLoader.java:32)
	at com.github.natanbc.lavadsp.natives.TimescaleConverter.<init>(TimescaleConverter.java:32)
	at com.github.natanbc.lavadsp.timescale.TimescalePcmAudioFilter.<init>(TimescalePcmAudioFilter.java:51)
	at me.JustAPie.CakeDJ.Commands.Music.NightcoreCommand.lambda$exec$0(NightcoreCommand.java:27)
	at me.JustAPie.CakeDJ.Commands.Music.NightcoreCommand$$Lambda$289/0x0000000000000000.buildChain(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.buildFragment(UserProvidedAudioFilters.java:40)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.<init>(UserProvidedAudioFilters.java:27)
	at com.sedmelluq.discord.lavaplayer.filter.AudioPipelineFactory.create(AudioPipelineFactory.java:40)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:196)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack$$Lambda$287/0x0000000000000000.performRead(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager$$Lambda$283/0x0000000000000000.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre NativeLibLoader      ERROR  Native library timescale: loading failed.
java.lang.UnsatisfiedLinkError: Required library was not found
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:161)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.nativeloader.DetectorLoader.load0(DetectorLoader.java:17)
	at com.github.natanbc.nativeloader.DetectorLoader.loadDetector(DetectorLoader.java:11)
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:150)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.lavadsp.natives.TimescaleNativeLibLoader.loadTimescaleLibrary(TimescaleNativeLibLoader.java:32)
	at com.github.natanbc.lavadsp.natives.TimescaleConverter.<init>(TimescaleConverter.java:32)
	at com.github.natanbc.lavadsp.timescale.TimescalePcmAudioFilter.<init>(TimescalePcmAudioFilter.java:51)
	at me.JustAPie.CakeDJ.Commands.Music.NightcoreCommand.lambda$exec$0(NightcoreCommand.java:27)
	at me.JustAPie.CakeDJ.Commands.Music.NightcoreCommand$$Lambda$289/0x0000000000000000.buildChain(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.buildFragment(UserProvidedAudioFilters.java:40)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.<init>(UserProvidedAudioFilters.java:27)
	at com.sedmelluq.discord.lavaplayer.filter.AudioPipelineFactory.create(AudioPipelineFactory.java:40)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:196)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack$$Lambda$287/0x0000000000000000.performRead(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager$$Lambda$283/0x0000000000000000.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
24-03-2021 09:59:59 lava-daemon-pool-playback-1-thre LocalAudioTrackExecu ERROR  Error in playback of fpO129tx0q8
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager$$Lambda$283/0x0000000000000000.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.71
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: AdoptOpenJDK
  java.version: 11.0.10
  java.runtime.version: 11.0.10+9
  java.vm.version: openj9-0.24.0
Caused by: java.lang.UnsatisfiedLinkError: Required library was not found
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:161)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.nativeloader.DetectorLoader.load0(DetectorLoader.java:17)
	at com.github.natanbc.nativeloader.DetectorLoader.loadDetector(DetectorLoader.java:11)
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:150)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.lavadsp.natives.TimescaleNativeLibLoader.loadTimescaleLibrary(TimescaleNativeLibLoader.java:32)
	at com.github.natanbc.lavadsp.natives.TimescaleConverter.<init>(TimescaleConverter.java:32)
	at com.github.natanbc.lavadsp.timescale.TimescalePcmAudioFilter.<init>(TimescalePcmAudioFilter.java:51)
	at me.JustAPie.CakeDJ.Commands.Music.NightcoreCommand.lambda$exec$0(NightcoreCommand.java:27)
	at me.JustAPie.CakeDJ.Commands.Music.NightcoreCommand$$Lambda$289/0x0000000000000000.buildChain(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.buildFragment(UserProvidedAudioFilters.java:40)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.<init>(UserProvidedAudioFilters.java:27)
	at com.sedmelluq.discord.lavaplayer.filter.AudioPipelineFactory.create(AudioPipelineFactory.java:40)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:196)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack$$Lambda$287/0x0000000000000000.performRead(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	... 5 common frames omitted
24-03-2021 09:59:59 Finalizer thread                 NativeResourceHolder WARN   Should have been closed before finalization (com.sedmelluq.discord.lavaplayer.natives.opus.OpusEncoder).
24-03-2021 09:59:59 Finalizer thread                 NativeResourceHolder WARN   Should have been closed before finalization (com.github.natanbc.lavadsp.natives.TimescaleConverter).
Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.UnsatisfiedLinkError: Required library was not found
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:161)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.nativeloader.DetectorLoader.load0(DetectorLoader.java:17)
	at com.github.natanbc.nativeloader.DetectorLoader.loadDetector(DetectorLoader.java:11)
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:150)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.lavadsp.natives.TimescaleNativeLibLoader.loadTimescaleLibrary(TimescaleNativeLibLoader.java:32)
	at com.github.natanbc.lavadsp.natives.TimescaleConverter.<init>(TimescaleConverter.java:32)
	at com.github.natanbc.lavadsp.timescale.TimescalePcmAudioFilter.<init>(TimescalePcmAudioFilter.java:51)
	at me.JustAPie.CakeDJ.Commands.Music.NightcoreCommand.lambda$exec$0(NightcoreCommand.java:27)
	at me.JustAPie.CakeDJ.Commands.Music.NightcoreCommand$$Lambda$289/0x0000000000000000.buildChain(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.buildFragment(UserProvidedAudioFilters.java:40)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.<init>(UserProvidedAudioFilters.java:27)
	at com.sedmelluq.discord.lavaplayer.filter.AudioPipelineFactory.create(AudioPipelineFactory.java:40)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:196)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack$$Lambda$287/0x0000000000000000.performRead(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager$$Lambda$283/0x0000000000000000.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by natanbc** [comment]
What files are present in `/natives/win-x86-64/` in your jar (just open it as a zip file)?

**Comment by JustAPieOP** [comment]
There are only 3 files:
![image](https://user-images.githubusercontent.com/57786194/112427435-27e16780-8d6c-11eb-8981-54d932e3c044.png)

**Comment by AlexIsOK** [comment]
Did you fix the issue?  I'm having it as well so it would be nice to know.

**Comment by JustAPieOP** [comment]
> Did you fix the issue? I'm having it as well so it would be nice to know.

Yes, i fixed it. Turns out i didn't package the jar properly because maven-shade-plugin ignores some .dll files
