### ISSUE TITLE
Required Library was not found 

### ISSUE THREAD

**Issue by DerKrisp** [natanbc/lavadsp#91]
Im trying to implement this Library but when i start the track, the following Exception appears.
```

Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.UnsatisfiedLinkError: Required library was not found
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:161)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.nativeloader.DetectorLoader.load0(DetectorLoader.java:17)
	at com.github.natanbc.nativeloader.DetectorLoader.loadDetector(DetectorLoader.java:11)
	at com.github.natanbc.nativeloader.NativeLibLoader.extractLibraryFromResources(NativeLibLoader.java:150)
	at com.github.natanbc.nativeloader.NativeLibLoader.load0(NativeLibLoader.java:110)
	at com.github.natanbc.nativeloader.NativeLibLoader.load(NativeLibLoader.java:73)
	at com.github.natanbc.lavadsp.natives.TimescaleNativeLibLoader.loadTimescaleLibrary(TimescaleNativeLibLoader.java:32)
	at com.github.natanbc.lavadsp.natives.TimescaleConverter.<init>(TimescaleConverter.java:32)
	at com.github.natanbc.lavadsp.timescale.TimescalePcmAudioFilter.<init>(TimescalePcmAudioFilter.java:51)
	at de.reservegames.krisp.krispymusic.commands.bySlash.music.speedCommand.lambda$onSlashCommandInteraction$0(speedCommand.java:41)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.buildFragment(UserProvidedAudioFilters.java:40)
	at com.sedmelluq.discord.lavaplayer.filter.UserProvidedAudioFilters.<init>(UserProvidedAudioFilters.java:27)
	at com.sedmelluq.discord.lavaplayer.filter.AudioPipelineFactory.create(AudioPipelineFactory.java:40)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:196)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

using the newest version of lavadsp and lavaplayer-fork.

**Comment by JustRed23** [comment]
Natives werent included in the jitpack version, so i made my own fork and added it
Check it out: https://github.com/JustRed23/lavadsp
